version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: forohub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: forohub
      MYSQL_USER: forohub
      MYSQL_PASSWORD: forohub123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - forohub-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: forohub-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=forohub
      - DB_PASSWORD=forohub123
      - JWT_SECRET=mySecretKey123456789012345678901234567890
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - forohub-network
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:

networks:
  forohub-network:
    driver: bridge